"""Calibrated risk model that sits beside the rules, never underneath them.

What it is
----------
A gradient-boosted classifier predicting P(needs critical care within 4 hours
of arrival), calibrated with isotonic regression on a held-out split, reported
with Brier score, AUC and a reliability curve.

What it is trained on
---------------------
A synthetic cohort generated by COHORT_SPEC below. This is stated loudly
because it matters: the model has not seen real patients, so its numbers are a
demonstration of the pipeline, not a clinical result. The generative process is
written out so a reviewer can judge whether it is circular. It is not derived
from the rules engine: outcomes are drawn from a latent physiological risk with
noise, and the rules engine never sees the labels.

Swapping in MIMIC-IV-ED is a config change (`load_cohort`), not a rewrite.

Why it cannot downgrade anyone
------------------------------
`blend()` takes the maximum of the rule acuity and the model acuity. The model
can raise a patient the rules under-rate. It can never lower one. That keeps
the asymmetric-cost design intact even if the model is wrong.
"""

from __future__ import annotations

import math
import random

COHORT_SPEC = """
Synthetic cohort, seed 20260830, n=6000.
  age      ~ mixture: 12% under 18 (log-uniform 0-17), 68% 18-64, 20% 65-95
  latent z ~ Normal(0,1) per patient, the unobserved "how sick"
  vitals   drawn from age-band normal ranges (APLS for under-18, adult
           reference otherwise) then shifted by z:
             hr   += z * 18 * band_hr_sd
             rr   += z * 5
             spo2 -= max(0, z) * 6
             sbp  -= max(0, z) * 22
             temp += z * 0.6 with a 15% fever spike arm
  15% of rows have 1-3 vitals set to None (real intake is incomplete)
  complaint / look drawn from a bank weighted by z
  outcome  P(critical within 4h) = sigmoid(1.9*z + 0.5*is_infant
             + 0.4*is_geriatric - 1.9), Bernoulli draw
Labels come from z, not from the rules engine. No leakage.
"""

FEATURES = [
    "age", "is_ped", "is_geri", "hr", "rr", "spo2", "sbp", "temp",
    "n_missing", "esi_proxy", "look_bad", "complaint_risk",
]

_SEED = 20260830
_state: dict = {}


def _sigmoid(x: float) -> float:
    return 1.0 / (1.0 + math.exp(-x))


def _band_ref(age: float):
    if age < 1:
        return (135, 35, 85)
    if age <= 2:
        return (125, 30, 90)
    if age <= 5:
        return (115, 27, 95)
    if age <= 12:
        return (100, 22, 105)
    if age < 18:
        return (80, 17, 112)
    if age >= 65:
        return (78, 17, 132)
    return (76, 16, 122)


def generate_cohort(n: int = 6000, seed: int = _SEED):
    """Synthetic rows per COHORT_SPEC. Returns (X, y)."""
    rng = random.Random(seed)
    x = []
    y = []
    for _ in range(n):
        r = rng.random()
        if r < 0.12:
            age = math.exp(rng.uniform(0, math.log(18)))
        elif r < 0.80:
            age = rng.uniform(18, 64)
        else:
            age = rng.uniform(65, 95)
        z = rng.gauss(0, 1)
        hr_ref, rr_ref, sbp_ref = _band_ref(age)
        hr = hr_ref + z * 18 + rng.gauss(0, 8)
        rr = rr_ref + z * 5 + rng.gauss(0, 2.5)
        spo2 = 98 - max(0.0, z) * 6 + rng.gauss(0, 1.5)
        sbp = sbp_ref - max(0.0, z) * 22 + rng.gauss(0, 10)
        temp = 36.8 + z * 0.6 + rng.gauss(0, 0.3)
        if rng.random() < 0.15:
            temp += rng.uniform(1.0, 2.5)

        vals = [hr, rr, spo2, sbp, temp]
        n_missing = 0
        if rng.random() < 0.15:
            n_missing = rng.randint(1, 3)
            for idx in rng.sample(range(5), n_missing):
                vals[idx] = None
        hr, rr, spo2, sbp, temp = vals

        look_bad = 1 if (z > 0.8 or rng.random() < 0.08) else 0
        complaint_risk = min(1.0, max(0.0, 0.5 + 0.4 * z + rng.gauss(0, 0.25)))
        esi_proxy = 5 - min(4, max(0, int(round(2.2 + 1.3 * z))))

        p = _sigmoid(1.9 * z + 0.5 * (age < 1) + 0.4 * (age >= 65) - 1.9)
        y.append(1 if rng.random() < p else 0)

        x.append([
            age, 1.0 if age < 18 else 0.0, 1.0 if age >= 65 else 0.0,
            _nan(hr), _nan(rr), _nan(spo2), _nan(sbp), _nan(temp),
            float(n_missing), float(esi_proxy), float(look_bad), complaint_risk,
        ])
    return x, y


def _nan(v):
    return float("nan") if v is None else float(v)


def load_cohort():
    """Swap point. Return (X, y). Today: synthetic. Tomorrow: MIMIC-IV-ED."""
    return generate_cohort()


def _fit():
    try:
        import numpy as np
        from sklearn.calibration import CalibratedClassifierCV
        from sklearn.ensemble import HistGradientBoostingClassifier
        from sklearn.metrics import brier_score_loss, roc_auc_score
        from sklearn.model_selection import train_test_split
    except Exception as exc:  # pragma: no cover
        return {"available": False, "error": str(exc)}

    x, y = load_cohort()
    x = np.array(x, dtype=float)
    y = np.array(y, dtype=int)
    xtr, xte, ytr, yte = train_test_split(x, y, test_size=0.3, random_state=_SEED, stratify=y)
    xfit, xcal, yfit, ycal = train_test_split(xtr, ytr, test_size=0.3, random_state=_SEED, stratify=ytr)

    base = HistGradientBoostingClassifier(
        max_iter=180, learning_rate=0.07, max_depth=4, random_state=_SEED
    )
    base.fit(xfit, yfit)
    try:
        from sklearn.frozen import FrozenEstimator
        cal = CalibratedClassifierCV(FrozenEstimator(base), method="isotonic")
    except Exception:
        cal = CalibratedClassifierCV(base, method="isotonic", cv="prefit")
    cal.fit(xcal, ycal)

    praw = base.predict_proba(xte)[:, 1]
    pcal = cal.predict_proba(xte)[:, 1]

    bins = 10
    curve = []
    edges = np.linspace(0, 1, bins + 1)
    for i in range(bins):
        m = (pcal >= edges[i]) & (pcal < edges[i + 1] if i < bins - 1 else pcal <= 1.0)
        if m.sum() < 5:
            continue
        curve.append({
            "bin": f"{edges[i]:.1f}-{edges[i+1]:.1f}",
            "predicted": round(float(pcal[m].mean()), 3),
            "observed": round(float(yte[m].mean()), 3),
            "n": int(m.sum()),
        })

    return {
        "available": True,
        "model": cal,
        "n_train": int(len(xfit)),
        "n_calib": int(len(xcal)),
        "n_test": int(len(xte)),
        "prevalence": round(float(y.mean()), 3),
        "auc": round(float(roc_auc_score(yte, pcal)), 3),
        "brier_raw": round(float(brier_score_loss(yte, praw)), 4),
        "brier_calibrated": round(float(brier_score_loss(yte, pcal)), 4),
        "reliability": curve,
        "features": FEATURES,
        "cohort": COHORT_SPEC.strip(),
    }


def model_state() -> dict:
    if "fit" not in _state:
        _state["fit"] = _fit()
    return _state["fit"]


def available() -> bool:
    return bool(model_state().get("available"))


def _row(p) -> list[float]:
    v = p.vitals
    from . import text as txt
    lookf = txt.look_features(p.look)
    compf = txt.complaint_features(p.complaint, p.tags)
    n_missing = len(v.missing_keys())
    return [
        float(p.age),
        1.0 if p.age < 18 else 0.0,
        1.0 if p.age >= 65 else 0.0,
        _nan(v.hr), _nan(v.rr), _nan(v.spo2), _nan(v.sbp), _nan(v.temp_c),
        float(n_missing), float(p.esi),
        1.0 if lookf["concerning"] else 0.0,
        min(1.0, compf["points"] / 25.0),
    ]


def risk(p) -> dict:
    """Calibrated P(critical within 4h) for one patient."""
    st = model_state()
    if not st.get("available"):
        return {"available": False, "prob": None, "reason": st.get("error", "sklearn missing")}
    import numpy as np
    prob = float(st["model"].predict_proba(np.array([_row(p)], dtype=float))[0, 1])
    return {
        "available": True,
        "prob": round(prob, 3),
        "auc": st["auc"],
        "brier": st["brier_calibrated"],
        "source": "GBM + isotonic, synthetic cohort",
    }


def risk_batch(patients) -> list[dict]:
    """One predict_proba for the whole room. Ranking calls this, not risk()."""
    st = model_state()
    if not st.get("available") or not patients:
        return [{"available": False, "prob": None} for _ in patients]
    import numpy as np
    rows = np.array([_row(p) for p in patients], dtype=float)
    probs = st["model"].predict_proba(rows)[:, 1]
    src = "GBM + isotonic, synthetic cohort"
    return [
        {"available": True, "prob": round(float(v), 3), "auc": st["auc"],
         "brier": st["brier_calibrated"], "source": src}
        for v in probs
    ]


# probability -> raw acuity points, so the two scales can be compared
POINTS_PER_PROB = 200.0

# the model only gets to speak when it is confident. Below this it is shown
# as a second opinion and nothing else.
LIFT_PROB_FLOOR = 0.45


def prob_to_points(prob: float) -> float:
    return POINTS_PER_PROB * prob


def blend(rule_raw: float, prob: float | None) -> dict:
    """Rules and model, max-combined, gated.

    The model can raise a patient the rules under-rate. It can never lower
    anyone, and it stays quiet below LIFT_PROB_FLOOR. If the model is wrong in
    the unsafe direction, the rules floor still holds.
    """
    if prob is None:
        return {"raw": rule_raw, "lifted": False, "model_raw": None, "disagree": False}
    mraw = prob_to_points(prob)
    lifted = prob >= LIFT_PROB_FLOOR and mraw > rule_raw
    disagree = mraw > rule_raw * 1.25 or (prob >= LIFT_PROB_FLOOR and rule_raw < 96)
    return {
        "raw": mraw if lifted else rule_raw,
        "lifted": lifted,
        "model_raw": round(mraw, 1),
        "disagree": bool(disagree),
    }
